### ISSUE TITLE
I've tried and haven't found the Copy Seed ID section 

### ISSUE THREAD

**Issue by KalvinThien** [theunkowndude/leonardoWrapper#2]
I just tried and I was able to transfer the seed ID, but when creating the image, can I copy this seed ID first?
Thank you very much 
I've tried and haven't found the Copy Seed ID section 
This part, when creating characters for the first time, will need to save the seed id, then when the next photos only need the seed id, it will create photos with the same character image 
copy seed id :
![image](https://github.com/user-attachments/assets/0eed3dbd-454e-4a23-8e54-70260927193a)

Example with same seed id:

![image](https://github.com/user-attachments/assets/ca761aef-c709-48ba-ad98-81f4e844174d)

**Comment by unknowndud3** [comment]
Hi KalvinThien,

just to make sure I understand it correctly, are you asking if its possible to copy the Seed-ID before generating an image that you are able to use that ID for other prompts?

**Comment by KalvinThien** [comment]
That's right, after creating a photo or video successfully, it will allow copying the seed ID. 
And from that seed id, it will be assigned to the next photo/video creation, at that time, just changing the prompt will change the character scene, but still the same design thanks to the seed ID 

> Hi KalvinThien,
> 
> just to make sure I understand it correctly, are you asking if its possible to copy the Seed-ID before generating an image that you are able to use that ID for other prompts?

**Comment by ghostboy-dev** [comment]
Hey Kelvin, but whats the issue there? You can just provide the Seed-ID as a parameter for the create image method.

**Comment by KalvinThien** [comment]
> Hey Kelvin, but whats the issue there? You can just provide the Seed-ID as a parameter for the create image method.



That's right, I was wrong when I chose to question my problem.

The goal of creating photos and copying seed ids automatically will help quite a bit in taking advantage of video creation automation.

Imagine when you enter a story, ChatGPT will analyze and return characters with their own design (their own seed id)
Then you ask ChatGPT to create prompts for each scene, and use the seed IDs of each character class to create scenes automatically with Leonardo. Finally convert it into video with Leonardo, Luma, vidu, klingai, runwayml ,...

I'm currently doing the same thing, but with selenium is the main one.

here I am contributing ideas to make the Leonardo wrapper even better.

**Comment by ghostboy-dev** [comment]
Nice, but  what should @anditv21 or @theunkowndude do? They already implemented the feature and it works for me <3

**Comment by KalvinThien** [comment]
> Nice, but what should @anditv21 or @theunkowndude do? They already implemented the feature and it works for me <3

It actually added the seed id. when creating photos. 
I only ask for the Copy Seed feature after creating a photo or video when necessary. This way, when necessary, I will copy the seed id automatically, and add the seed id of the process afterwards. 

The wrapper I found to be pretty perfect, as it's a lot more efficient than selenium.

**Comment by anditv21** [comment]
> > Nice, but what should @anditv21 or @theunkowndude do? They already implemented the feature and it works for me <3
> 
> 
> 
> It actually added the seed id. when creating photos. 
> 
> I only ask for the Copy Seed feature after creating a photo or video when necessary. This way, when necessary, I will copy the seed id automatically, and add the seed id of the process afterwards. 
> 
> 
> 
> The wrapper I found to be pretty perfect, as it's a lot more efficient than selenium. 
> 
> 
> 
> 

So have I understood correctly? You want us to create a function that automatically copies the seed id to your clipboard after the generation of the image?

**Comment by anditv21** [comment]
And why should this be added to the wrapper? The response already contains the seed id.
So you could just copy it to the clipboard with a small code snippet. right?

![CItFMzt](https://github.com/user-attachments/assets/0ff5586b-8e6c-4a08-9eed-b61f68fe09fc)

**Comment by KalvinThien** [comment]
> And why should this be added to the lib? The response already contains the seed id. So you could just copy it to the clipboard with a small code snippet. right?
> 
> ![CItFMzt](https://private-user-images.githubusercontent.com/75949923/355492295-0ff5586b-8e6c-4a08-9eed-b61f68fe09fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTY0ODIsIm5iZiI6MTcyMjk1NjE4MiwicGF0aCI6Ii83NTk0OTkyMy8zNTU0OTIyOTUtMGZmNTU4NmItOGU2Yy00YTA4LTllZWQtYjYxZjY4ZmUwOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0NTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOTJlNjUzMjk0NjNjNWQ3N2Q1ZGNlZmFjMjE3MmQzNzg4NGVjOWE2YzI5OWZiMjdiMDlhYmQ2NGFjNzhkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Qr7izrc4_iA-XOpBPMnixyMMuJBlaS44JrbEO9uHpU)

Oh, sorry for not paying attention, because I didn't print out the feedback so I didn't notice that it was returned
