### ISSUE TITLE
Is it possible to select these presets in the Leonardo wrapper?

### ISSUE THREAD

**Issue by KalvinThien** [theunkowndude/leonardoWrapper#4]
hi, the presets will help the photo to be in the right direction 
.
For some presets such as stock photos, photos can be sent to create uniform content.

In models.md I see that there is a Leonardo Phoenix option but no other options

![image](https://github.com/user-attachments/assets/75872e0c-8cf3-4d2b-83a1-21e845f302d6)
![image](https://github.com/user-attachments/assets/48e25f5b-bbbc-4364-87de-4b88ad4fbc42)

**Comment by unknowndud3** [comment]
Its currently not supported.

**Comment by KalvinThien** [comment]
thanks for that
